# kerasを使って2019年1月分のトレーニング

In [10]:
import numpy as np
import pandas as pd
import pickle

import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [11]:
train_df = pd.read_csv('data/201901.csv')
train_df = train_df.drop('Unnamed: 0', axis=1)
train_df = train_df[train_df.game == 7]
train_df = train_df.drop(['east_end', 'north_end', 'south_end', 'west_end', 'game'], axis=1)

In [12]:
train_df

east  north  south  west  game_result
10       264    141    258   337           14
37       301    205    116   378           13
38       296    220    111   373           13
54       472    183    326    19            7
62       393    259    178   170            4
...      ...    ...    ...   ...          ...
151490   187     61    371   381           23
151502   267    289    328   116           15
151511   191    173    324   312            9
151512   165    251    298   286            9
151513   165    274    275   286            9

[14009 rows x 5 columns]

In [13]:
data_X = train_df.iloc[:, 0:4]
data_y = train_df.iloc[:, 4]

In [14]:
standard_scaler = preprocessing.StandardScaler()
data_X = standard_scaler.fit_transform(data_X)

In [15]:
train_X, test_X, train_y, test_y = train_test_split(data_X, data_y, test_size=0.3, random_state=123)

In [16]:
train_X

array([[-0.21071566,  0.60255329, -0.02946168, -0.29504215],
       [ 0.10133241, -1.06160751,  2.50828249, -1.64340413],
       [ 1.69530768, -1.68104514,  0.78594464, -1.01916247],
       ...,
       [-1.22276345,  3.64426943, -1.08616172, -0.97754636],
       [ 0.4724166 ,  0.90764944, -0.36228059, -0.91096058],
       [-0.53963119,  1.59180444, -0.92807274,  0.03788673]])

In [19]:
model = Sequential()
# Dense(64) は，64個のhidden unitを持つ全結合層です．
# 最初のlayerでは，想定する入力データshapeを指定する必要があり，ここでは20次元としてます．
model.add(Dense(128, activation='relu', input_dim=4))
model.add(Dropout(0.1))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.1))
model.add(Dense(24, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)
model.compile(loss='categorical_crossentropy',
              optimizer=sgd,
              metrics=['accuracy'])

# history = model.fit(x.values, pd.get_dummies(y).values,epochs=20,batch_size=128)
history = model.fit(train_X, pd.get_dummies(train_y).values,epochs=32, validation_data=(test_X, pd.get_dummies(test_y)), batch_size=128)
# score = model.evaluate(x_test, y_test, batch_size=128)

Epoch 1/32
77/77 [==============================] - 0s 6ms/step - loss: 3.0876 - accuracy: 0.1180 - val_loss: 2.9698 - val_accuracy: 0.1961
Epoch 2/32
77/77 [==============================] - 0s 5ms/step - loss: 2.8565 - accuracy: 0.2089 - val_loss: 2.7387 - val_accuracy: 0.2472
Epoch 3/32
77/77 [==============================] - 0s 5ms/step - loss: 2.6588 - accuracy: 0.2437 - val_loss: 2.6018 - val_accuracy: 0.2624
Epoch 4/32
77/77 [==============================] - 0s 4ms/step - loss: 2.5507 - accuracy: 0.2505 - val_loss: 2.5065 - val_accuracy: 0.2684
Epoch 5/32
77/77 [==============================] - 0s 4ms/step - loss: 2.4672 - accuracy: 0.2590 - val_loss: 2.4249 - val_accuracy: 0.2772
Epoch 6/32
77/77 [==============================] - 0s 5ms/step - loss: 2.4094 - accuracy: 0.2581 - val_loss: 2.3776 - val_accuracy: 0.2731
Epoch 7/32
77/77 [==============================] - 0s 5ms/step - loss: 2.3659 - accuracy: 0.2688 - val_loss: 2.3395 - val_accuracy: 0.2808
Epoch 8/32
77/77 [==

In [25]:
model.predict([[0.4, 0.2, 0.3 , 0.1]])

array([[0.22416872, 0.2723421 , 0.05197909, 0.01432255, 0.07351737,
        0.01506102, 0.04791537, 0.08218122, 0.00497316, 0.00041538,
        0.01000331, 0.00060073, 0.07763412, 0.01448002, 0.01682159,
        0.00057312, 0.00790447, 0.00092029, 0.06598855, 0.00779397,
        0.00773673, 0.00040509, 0.00182934, 0.00043273]], dtype=float32)

In [5]:
x.values

array([[ 1.47,  0.95,  2.26],
       [ 1.83,  2.47,  3.46],
       [ 0.41,  1.14,  0.73],
       ...,
       [-3.62, -2.09, -3.05],
       [-2.4 ,  0.8 , -0.4 ],
       [ 0.53,  2.52,  1.23]])

In [6]:
y.values

array([ 2,  0,  9, ..., 21, 13,  7])